services:

    nginx:
      container_name: nginx
      build: ./srcs/nginx
      ports:
        - "8443:443"        # Point d'entrée HTTPS public
      depends_on:
        - gateway
        - front
      networks:
        - frontend
        - backend

    gateway:
      container_name: gateway
      build: ./srcs/back/gateway
      expose:
        - "8080"            # Port interne uniquement, accessible depuis nginx  
      depends_on:
        auth:
          condition: service_healthy
        user:
          condition: service_healthy
        game:
          condition: service_healthy
        chat:
          condition: service_healthy
      env_file: 
        - .env
      networks: 
        - backend 

    front:
      container_name: front
      build: ./srcs/front
      expose:
        - "80"
      depends_on:
        - gateway
      networks: 
        - frontend

    auth:
      container_name: auth
      build: ./srcs/back/auth
      expose:
        - "3001"
      env_file: 
        - .env
      environment:
        - DATABASE_URL=/app/data/auth.sqlite
      networks: 
        - backend
      dns:
        - 8.8.8.8
        - 1.1.1.1
      healthcheck:
        test: ["CMD", "sqlite3", "/app/data/auth.sqlite", "SELECT 1;"]
        interval: 2s
        retries: 20

    chat:
      container_name: chat
      build: ./srcs/back/chat
      expose:
        - "3002"
      env_file: 
        - .env
      environment:
        - DATABASE_URL=/app/data/chat.sqlite
      networks: 
        - backend
      healthcheck:
        test: ["CMD", "sqlite3", "/app/data/chat.sqlite", "SELECT 1;"]
        interval: 2s
        retries: 20

    game:
      container_name: game
      build: ./srcs/back/game
      expose:
        - "3003"
      env_file: 
        - .env
      environment:
        - DATABASE_URL=/app/data/game.sqlite
      networks:
        - backend
      healthcheck:
        test: ["CMD", "sqlite3", "/app/data/game.sqlite", "SELECT 1;"]
        interval: 2s
        retries: 20

    user:
      container_name: user
      build: ./srcs/back/user
      expose:
        - "3004"
      env_file: 
        - .env
      environment:
        - DATABASE_URL=/app/data/user.sqlite
      networks: 
        - backend
      healthcheck:
        test: ["CMD", "sqlite3", "/app/data/user.sqlite", "SELECT 1;"]
        interval: 2s
        retries: 20
    
networks:
  frontend:
    name: transcendence_frontend
    driver: bridge
  backend:
    name: transcendence_backend
    driver: bridge
